// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QatratHayat.Infrastructure.Persistence;

#nullable disable

namespace QatratHayat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420053130_fixNaming")]
    partial class fixNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Beneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MergedIntoUserId")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MergedIntoUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("int");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoctorApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("int");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShortagePhase1At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShortagePhase2At")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitsNeeded")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("RequesterUserId");

                    b.ToTable("BloodRequests");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.BloodUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AllocatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AllocatedToRequestId")
                        .HasColumnType("int");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeallocationNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DisposalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisposalReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DisposedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnitStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AllocatedToRequestId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DisposedByEmployeeId");

                    b.HasIndex("DonationId")
                        .IsUnique();

                    b.ToTable("BloodUnits");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BranchNameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BranchNameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GPSLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("GPSLng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ManagerUserId")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.BranchWorkingHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchWorkingHours");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.CampaignTargetBloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignTargetBloodTypes");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.DeferralRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DecisionSource")
                        .HasColumnType("int");

                    b.Property<int>("DeferralType")
                        .HasColumnType("int");

                    b.Property<int>("DonorProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ScreeningQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("ScreeningSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("DonorProfileId");

                    b.HasIndex("ScreeningQuestionId");

                    b.HasIndex("ScreeningSessionId");

                    b.ToTable("DeferralRecords");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodRequestId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonationType")
                        .HasColumnType("int");

                    b.Property<int>("DonorProfileId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeUserId")
                        .HasColumnType("int");

                    b.Property<string>("FinalDecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FinalEligibilityStatus")
                        .HasColumnType("int");

                    b.Property<int>("InitialEligibilityStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodRequestId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("DonorProfileId");

                    b.HasIndex("EmployeeUserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.DonationIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonationIntentStatus")
                        .HasColumnType("int");

                    b.Property<int>("DonationType")
                        .HasColumnType("int");

                    b.Property<int>("DonorProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodRequestId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("DonorProfileId");

                    b.ToTable("DonationIntents");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.DonorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BloodTypeConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BloodTypeConfirmedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("BloodTypeStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonationCount")
                        .HasColumnType("int");

                    b.Property<int>("EligibilityStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextEligibleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermanentDeferralReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("iAgree")
                        .HasColumnType("bit");

                    b.Property<bool>("iConfirm")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeConfirmedByEmployeeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DonorProfiles");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAR")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HospitalNameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HospitalNameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.NationalRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsJordanian")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("NationalRegistries");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentAr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LinkedEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedEntityType")
                        .HasColumnType("int");

                    b.Property<int>("NotificationChannel")
                        .HasColumnType("int");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("int");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.ScreeningAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Answer")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConditionalDateValue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonationIntentId")
                        .HasColumnType("int");

                    b.Property<int?>("DonorProfileId")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningSessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationIntentId");

                    b.HasIndex("DonorProfileId");

                    b.HasIndex("ScreeningQuestionId");

                    b.HasIndex("ScreeningSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ScreeningAnswers");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.ScreeningQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalTextLabelAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AdditionalTextLabelEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConditionalDateLabelAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConditionalDateLabelEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecisionMode")
                        .HasColumnType("int");

                    b.Property<int?>("DeferralPeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("DeferralType")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForFemaleOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresAdditionalText")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresDateValue")
                        .HasColumnType("bit");

                    b.Property<int>("SessionType")
                        .HasColumnType("int");

                    b.Property<string>("TextAr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ScreeningQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 1,
                            DeferralType = 3,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 1,
                            TextAr = "هل سبق لك تبرعت بالدم؟",
                            TextEn = "Have you donated blood before?"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalTextLabelAr = "",
                            AdditionalTextLabelEn = "",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 1,
                            TextAr = "هل حدثت لك ردود فعل نتيجة التبرع مثل الدوخة أو الإغماء أو غيرها؟",
                            TextEn = "Have you ever experienced reactions after blood donation such as dizziness, fainting, or others?"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalTextLabelAr = "اذكر اسم المرض",
                            AdditionalTextLabelEn = "Please specify the condition",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = true,
                            RequiresDateValue = false,
                            SessionType = 1,
                            TextAr = "هل أنت مصاب بأمراض الدم الوراثية مثل الثلاسيميا أو فقر الدم المنجلي أو فقر الدم المزمن أو غيرها؟",
                            TextEn = "Do you have hereditary blood disorders such as thalassemia, sickle cell disease, chronic anemia, or others?"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalTextLabelAr = "",
                            AdditionalTextLabelEn = "",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralType = 2,
                            DisplayOrder = 4,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 1,
                            TextAr = "هل أنت مصاب بأمراض نزف الدم أو أي نقص خلقي في أحد عوامل التخثر مثل الهيموفيليا أو غيرها؟",
                            TextEn = "Do you have bleeding disorders or congenital clotting factor deficiencies such as hemophilia or others?"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalTextLabelAr = "اذكر اسم المرض",
                            AdditionalTextLabelEn = "Please specify the condition",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 5,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = true,
                            RequiresDateValue = false,
                            SessionType = 1,
                            TextAr = "هل أنت مصاب بأمراض المناعة الذاتية مثل مرض بهجت أو الذئبة أو حمى البحر الأبيض المتوسط أو الروماتيزم أو الصدفية أو البهاق أو الثعلبة أو غيرها؟",
                            TextEn = "Do you have autoimmune diseases such as Behçet’s disease, lupus, familial Mediterranean fever, rheumatism, psoriasis, vitiligo, alopecia, or others?"
                        },
                        new
                        {
                            Id = 6,
                            AdditionalTextLabelAr = "اذكر نوع الحساسية",
                            AdditionalTextLabelEn = "Please specify the allergy",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 6,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = true,
                            RequiresDateValue = false,
                            SessionType = 1,
                            TextAr = "هل أنت مصاب بأمراض الحساسية المزمنة والشديدة؟",
                            TextEn = "Do you have severe or chronic allergic conditions?"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 7,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 1,
                            TextAr = "هل تشكو من نوبات إغماء أو تشنج؟",
                            TextEn = "Do you suffer from fainting episodes or seizures?"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 1,
                            DeferralType = 3,
                            DisplayOrder = 8,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 1,
                            TextAr = "هل تسافر كثيرًا إلى الخارج؟",
                            TextEn = "Do you travel abroad frequently?"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "هل صحتك اليوم ليست جيدة؟",
                            TextEn = "Are you feeling unwell today?"
                        },
                        new
                        {
                            Id = 102,
                            ConditionalDateLabelAr = "تاريخ الإصابة أو انتهاء العلاج",
                            ConditionalDateLabelEn = "Date of illness or completion of treatment",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralPeriodDays = 1095,
                            DeferralType = 1,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل سبق وأن أُصبت بالملاريا خلال الثلاث سنوات الماضية؟",
                            TextEn = "Have you had malaria during the past 3 years?"
                        },
                        new
                        {
                            Id = 103,
                            ConditionalDateLabelAr = "تاريخ العودة من السفر",
                            ConditionalDateLabelEn = "Date of return from travel",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralPeriodDays = 90,
                            DeferralType = 1,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل سافرت مؤخرًا إلى منطقة يتفشى فيها مرض الملاريا؟",
                            TextEn = "Have you recently traveled to an area where malaria is endemic?"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 4,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "هل سبق وأن أُصبت بالحمى المالطية أو حمى التيفوئيد؟",
                            TextEn = "Have you ever had brucellosis or typhoid fever?"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 5,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "هل سبق وأن أُصبت باليرقان؟",
                            TextEn = "Have you ever had jaundice?"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 6,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "هل سبق وأن أُصبت بالتهاب الكبد الفيروسي؟",
                            TextEn = "Have you ever had viral hepatitis?"
                        },
                        new
                        {
                            Id = 107,
                            ConditionalDateLabelAr = "تاريخ آخر مخالطة",
                            ConditionalDateLabelEn = "Date of last contact",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralPeriodDays = 365,
                            DeferralType = 1,
                            DisplayOrder = 7,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل خالطت شخصًا مصابًا بالتهاب الكبد الفيروسي خلال الاثني عشر شهرًا الماضية؟",
                            TextEn = "Have you had close contact with someone with viral hepatitis during the past 12 months?"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralType = 2,
                            DisplayOrder = 8,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "هل أنت مصاب بأحد الأمراض المعدية التي تنتقل عن طريق الدم مثل الإيدز أو السفلس؟",
                            TextEn = "Do you have any blood-borne infectious diseases such as HIV/AIDS or syphilis?"
                        },
                        new
                        {
                            Id = 109,
                            AdditionalTextLabelAr = "اذكر الحالة المرضية",
                            AdditionalTextLabelEn = "Please specify the condition",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 9,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = true,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "هل أنت مصاب بأي من أمراض الرئة أو القلب أو الكلى أو السكري المعتمد على الإنسولين أو ارتفاع ضغط الدم؟",
                            TextEn = "Do you have any of the following conditions: lung disease, heart disease, kidney disease, insulin-dependent diabetes, or high blood pressure?"
                        },
                        new
                        {
                            Id = 110,
                            AdditionalTextLabelAr = "اذكر اسم الدواء",
                            AdditionalTextLabelEn = "Please specify the medication",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 10,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = true,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "هل تتناول أدوية لأي مرض؟",
                            TextEn = "Are you taking any medications for any illness?"
                        },
                        new
                        {
                            Id = 111,
                            ConditionalDateLabelAr = "تاريخ آخر جرعة",
                            ConditionalDateLabelEn = "Date of last dose",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 11,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل تناولت أسبرين أو أي دواء يحتوي على مكونات الأسبرين خلال الثلاثة أيام الماضية؟",
                            TextEn = "Have you taken aspirin or any medication containing aspirin during the past 3 days?"
                        },
                        new
                        {
                            Id = 112,
                            AdditionalTextLabelAr = "اذكر اسم الدواء",
                            AdditionalTextLabelEn = "Please specify the medication",
                            ConditionalDateLabelAr = "تاريخ آخر جرعة",
                            ConditionalDateLabelEn = "Date of last dose",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 12,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = true,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل تناولت أي مسكنات للألم أو مضادات للالتهاب خلال الثلاثة أيام الماضية؟",
                            TextEn = "Have you taken any painkillers or anti-inflammatory medications during the past 3 days?"
                        },
                        new
                        {
                            Id = 113,
                            ConditionalDateLabelAr = "تاريخ الإجراء",
                            ConditionalDateLabelEn = "Date of the procedure",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 13,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل خلعت سنًا أو أجريت علاجًا للأسنان خلال السبعة أيام الماضية؟",
                            TextEn = "Have you had a tooth extraction or dental treatment during the past 7 days?"
                        },
                        new
                        {
                            Id = 114,
                            ConditionalDateLabelAr = "تاريخ الإجراء",
                            ConditionalDateLabelEn = "Date of the procedure",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralPeriodDays = 365,
                            DeferralType = 1,
                            DisplayOrder = 14,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل تعرضت لثقب بالأذن أو الجلد أو للعلاج بالإبر الصينية خلال الاثني عشر شهرًا الماضية؟",
                            TextEn = "Have you had ear/body piercing or acupuncture during the past 12 months?"
                        },
                        new
                        {
                            Id = 115,
                            AdditionalTextLabelAr = "اذكر نوع العملية",
                            AdditionalTextLabelEn = "Please specify the type of surgery",
                            ConditionalDateLabelAr = "تاريخ العملية",
                            ConditionalDateLabelEn = "Date of surgery",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 15,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = true,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل أُجريت لك عملية جراحية خلال الاثني عشر شهرًا الماضية؟",
                            TextEn = "Have you had surgery during the past 12 months?"
                        },
                        new
                        {
                            Id = 116,
                            ConditionalDateLabelAr = "تاريخ نقل الدم",
                            ConditionalDateLabelEn = "Date of transfusion",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralPeriodDays = 365,
                            DeferralType = 1,
                            DisplayOrder = 16,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل تلقيت نقل دم أو مشتقاته خلال الاثني عشر شهرًا الماضية؟",
                            TextEn = "Have you received a blood transfusion or blood products during the past 12 months?"
                        },
                        new
                        {
                            Id = 117,
                            ConditionalDateLabelAr = "تاريخ الحجامة",
                            ConditionalDateLabelEn = "Date of cupping",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 17,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل عملت حجامة خلال الثمانية أشهر الماضية؟",
                            TextEn = "Have you had cupping therapy during the past 8 months?"
                        },
                        new
                        {
                            Id = 118,
                            ConditionalDateLabelAr = "تاريخ الوشم",
                            ConditionalDateLabelEn = "Date of tattoo",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralPeriodDays = 365,
                            DeferralType = 1,
                            DisplayOrder = 18,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل عملت وشمًا خلال الاثني عشر شهرًا الماضية؟",
                            TextEn = "Have you had a tattoo during the past 12 months?"
                        },
                        new
                        {
                            Id = 119,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralType = 2,
                            DisplayOrder = 19,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "هل استخدمت إبرًا لأخذ أي نوع من المخدرات عن طريق الوريد أو تحت الجلد؟",
                            TextEn = "Have you ever used needles to take non-prescribed drugs intravenously or under the skin?"
                        },
                        new
                        {
                            Id = 120,
                            AdditionalTextLabelAr = "اذكر اسم المطعوم",
                            AdditionalTextLabelEn = "Please specify the vaccine",
                            ConditionalDateLabelAr = "تاريخ المطعوم",
                            ConditionalDateLabelEn = "Date of vaccination",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 20,
                            IsActive = true,
                            IsForFemaleOnly = false,
                            RequiresAdditionalText = true,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "هل أخذت أي مطعوم خلال الأربعة أسابيع الماضية؟",
                            TextEn = "Have you received any vaccine during the past 4 weeks?"
                        },
                        new
                        {
                            Id = 121,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralType = 1,
                            DisplayOrder = 21,
                            IsActive = true,
                            IsForFemaleOnly = true,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "للنساء: هل أنتِ حامل الآن؟",
                            TextEn = "For women: Are you currently pregnant?"
                        },
                        new
                        {
                            Id = 122,
                            ConditionalDateLabelAr = "تاريخ آخر حمل أو إجهاض",
                            ConditionalDateLabelEn = "Date of last pregnancy or miscarriage",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 2,
                            DeferralPeriodDays = 270,
                            DeferralType = 1,
                            DisplayOrder = 22,
                            IsActive = true,
                            IsForFemaleOnly = true,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "للنساء: هل حدث حمل أو إجهاض خلال الأشهر التسعة الماضية؟",
                            TextEn = "For women: Have you been pregnant or had a miscarriage during the past 9 months?"
                        },
                        new
                        {
                            Id = 123,
                            ConditionalDateLabelAr = "تاريخ انتهاء الرضاعة الطبيعية",
                            ConditionalDateLabelEn = "Date breastfeeding ended",
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 23,
                            IsActive = true,
                            IsForFemaleOnly = true,
                            RequiresAdditionalText = false,
                            RequiresDateValue = true,
                            SessionType = 2,
                            TextAr = "للنساء: هل انتهت الرضاعة الطبيعية قبل أقل من ثلاثة أشهر؟",
                            TextEn = "For women: Did breastfeeding end less than 3 months ago?"
                        },
                        new
                        {
                            Id = 124,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecisionMode = 3,
                            DeferralType = 3,
                            DisplayOrder = 24,
                            IsActive = true,
                            IsForFemaleOnly = true,
                            RequiresAdditionalText = false,
                            RequiresDateValue = false,
                            SessionType = 2,
                            TextAr = "للنساء: هل تعانين الآن من الدورة الشهرية مع زيادة في كمية الدم المفقودة؟",
                            TextEn = "For women: Are you currently menstruating with increased blood loss?"
                        });
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.ScreeningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonationIntentId")
                        .HasColumnType("int");

                    b.Property<int?>("DonorProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ResultEligibilityStatus")
                        .HasColumnType("int");

                    b.Property<int>("SessionType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationIntentId");

                    b.HasIndex("DonorProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("ScreeningSessions");
                });

            modelBuilder.Entity("QatratHayat.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Citizen",
                            NormalizedName = "CITIZEN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = 4,
                            Name = "BranchManager",
                            NormalizedName = "BRANCHMANAGER"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("QatratHayat.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Beneficiary", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.BloodRequest", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.Beneficiary", "Beneficiary")
                        .WithMany("BloodRequests")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QatratHayat.Domain.Entities.Hospital", "Hospital")
                        .WithMany("BloodRequests")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("CreatedBloodRequests")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.BloodUnit", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.BloodRequest", "BloodRequest")
                        .WithMany("BloodUnits")
                        .HasForeignKey("AllocatedToRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.Branch", "Branch")
                        .WithMany("BloodUnits")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DisposedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.Donation", "Donation")
                        .WithOne("BloodUnit")
                        .HasForeignKey("QatratHayat.Domain.Entities.BloodUnit", "DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("Branch");

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Branch", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.BranchWorkingHour", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.Branch", "Branch")
                        .WithMany("WorkingHours")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.Branch", "Branch")
                        .WithMany("Campaigns")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("CreatedCampaigns")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.CampaignTargetBloodType", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.Campaign", "Campaign")
                        .WithMany("TargetBloodTypes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.DeferralRecord", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.DonorProfile", "DonorProfile")
                        .WithMany("DeferralRecords")
                        .HasForeignKey("DonorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QatratHayat.Domain.Entities.ScreeningQuestion", "ScreeningQuestion")
                        .WithMany()
                        .HasForeignKey("ScreeningQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.ScreeningSession", "ScreeningSession")
                        .WithMany()
                        .HasForeignKey("ScreeningSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonorProfile");

                    b.Navigation("ScreeningQuestion");

                    b.Navigation("ScreeningSession");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Donation", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.BloodRequest", "BloodRequest")
                        .WithMany("Donations")
                        .HasForeignKey("BloodRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.Branch", "Branch")
                        .WithMany("Donations")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QatratHayat.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Donations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.DonorProfile", "DonorProfile")
                        .WithMany("Donations")
                        .HasForeignKey("DonorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("ProcessedDonations")
                        .HasForeignKey("EmployeeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("Branch");

                    b.Navigation("Campaign");

                    b.Navigation("DonorProfile");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.DonationIntent", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.BloodRequest", "BloodRequest")
                        .WithMany("DonationIntents")
                        .HasForeignKey("BloodRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.Campaign", "Campaign")
                        .WithMany("DonationIntents")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.DonorProfile", "DonorProfile")
                        .WithMany("DonationIntents")
                        .HasForeignKey("DonorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodRequest");

                    b.Navigation("Campaign");

                    b.Navigation("DonorProfile");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.DonorProfile", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("BloodTypeConfirmedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("DonorProfile")
                        .HasForeignKey("QatratHayat.Domain.Entities.DonorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Hospital", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.Branch", "Branch")
                        .WithMany("Hospitals")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Notification", b =>
                {
                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.ScreeningAnswer", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.DonationIntent", "DonationIntent")
                        .WithMany("ScreeningAnswers")
                        .HasForeignKey("DonationIntentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.DonorProfile", "DonorProfile")
                        .WithMany("ScreeningAnswers")
                        .HasForeignKey("DonorProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.ScreeningQuestion", "ScreeningQuestion")
                        .WithMany("ScreeningAnswers")
                        .HasForeignKey("ScreeningQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QatratHayat.Domain.Entities.ScreeningSession", "ScreeningSession")
                        .WithMany("Answers")
                        .HasForeignKey("ScreeningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("ScreeningAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonationIntent");

                    b.Navigation("DonorProfile");

                    b.Navigation("ScreeningQuestion");

                    b.Navigation("ScreeningSession");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.ScreeningSession", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.DonationIntent", "DonationIntent")
                        .WithMany("ScreeningSessions")
                        .HasForeignKey("DonationIntentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.DonorProfile", "DonorProfile")
                        .WithMany("ScreeningSessions")
                        .HasForeignKey("DonorProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("ScreeningSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonationIntent");

                    b.Navigation("DonorProfile");
                });

            modelBuilder.Entity("QatratHayat.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("QatratHayat.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QatratHayat.Domain.Entities.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Beneficiary", b =>
                {
                    b.Navigation("BloodRequests");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.BloodRequest", b =>
                {
                    b.Navigation("BloodUnits");

                    b.Navigation("DonationIntents");

                    b.Navigation("Donations");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Branch", b =>
                {
                    b.Navigation("BloodUnits");

                    b.Navigation("Campaigns");

                    b.Navigation("Donations");

                    b.Navigation("Hospitals");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("DonationIntents");

                    b.Navigation("Donations");

                    b.Navigation("TargetBloodTypes");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Donation", b =>
                {
                    b.Navigation("BloodUnit")
                        .IsRequired();
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.DonationIntent", b =>
                {
                    b.Navigation("ScreeningAnswers");

                    b.Navigation("ScreeningSessions");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.DonorProfile", b =>
                {
                    b.Navigation("DeferralRecords");

                    b.Navigation("DonationIntents");

                    b.Navigation("Donations");

                    b.Navigation("ScreeningAnswers");

                    b.Navigation("ScreeningSessions");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.Hospital", b =>
                {
                    b.Navigation("BloodRequests");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.ScreeningQuestion", b =>
                {
                    b.Navigation("ScreeningAnswers");
                });

            modelBuilder.Entity("QatratHayat.Domain.Entities.ScreeningSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("QatratHayat.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("CreatedBloodRequests");

                    b.Navigation("CreatedCampaigns");

                    b.Navigation("DonorProfile");

                    b.Navigation("Notifications");

                    b.Navigation("ProcessedDonations");

                    b.Navigation("ScreeningAnswers");

                    b.Navigation("ScreeningSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
